### ISSUE TITLE
Getting an NoneType error while testing with my images

### ISSUE THREAD

**Issue by dinushazoomi** [xavysp/DexiNed#132]
Hi all, I am getting an error while trying to edge detect my own images. I followed the instructions given on the Readme and put my images in the data folder. The error seems to be generation from the data loader.

Following is the error massage

```
Traceback (most recent call last):
  File "/content/DexiNed/main.py", line 487, in <module>
    main(args)
  File "/content/DexiNed/main.py", line 410, in main
    test(checkpoint_path, dataloader_val, model, device, output_dir, args)
  File "/content/DexiNed/main.py", line 127, in test
    for i in enumerate(dataloader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/DexiNed/datasets.py", line 263, in __getitem__
    im_shape = [image.shape[0], image.shape[1]]
AttributeError: 'NoneType' object has no attribute 'shape'
```

Any help on this would be highly appreciated
Thank you

**Comment by dinushazoomi** [comment]
Found the solution, it was not an error with Dixined, I was running it in the colab, It generated some files `.ipynb_checkpoints`, when uploading images to it. use !rm -rf `find -type d -name .ipynb_checkpoints` command before running it.

```
%cd /content/DexiNed
!rm -rf `find -type d -name .ipynb_checkpoints`
!python main.py --choose_test_data=-1
```
