### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 768, 768, 3) for Tensor 'Placeholder:0', which has shape '(?, 224, 224, 3)'

### ISSUE THREAD

**Issue by kandilidinesh** [xavysp/DexiNed#26]
`[28 May 2020 15h54m46s][INFO]Done restoring DexiNed model from checkpoints/DXN_CDIBD/train/DXN-79999
[28 May 2020 15h54m46s][INFO] Enterely testing set-up from /home/cdi/dinesh/dexined-aug/dataset/CDIBD/boundary/test_list.lst, size: 100
[28 May 2020 15h54m46s][INFO]testing set-up from /home/cdi/dinesh/dexined-aug/dataset/CDIBD/boundary/test_list.lst, size: 100
[28 May 2020 15h54m46s][INFO]Writing PNGs at None
Traceback (most recent call last):
  File "run_model.py", line 138, in <module>
    main(args=args)
  File "run_model.py", line 129, in main
    tester.run(sess)
  File "/home/cdi/dinesh/dexined-aug/test.py", line 55, in run
    edgemap = session.run(self.model.predictions, feed_dict={self.model.images: [im]})
  File "/home/cdi/anaconda3/envs/Dexi_Py37_Tfg113/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/cdi/anaconda3/envs/Dexi_Py37_Tfg113/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 768, 768, 3) for Tensor 'Placeholder:0', which has shape '(?, 224, 224, 3)'`

I am getting this error when I am trying to test my trained model with test image dataset of 100 images.

**Comment by xavysp** [comment]
Hi, set the 'Placeholder:0' with (?, 768, 768, 3) ?=None

**Comment by xavysp** [comment]
After waiting 15 days I close this issue
