### ISSUE TITLE
I trained bsds dataset with dexined, but errors occoured when I used the pretrained model to test

### ISSUE THREAD

**Issue by nywang2019** [xavysp/DexiNed#33]
i trained the bsds dataset successfully, but i failed to test with it.  here are errors,  i don't know why,  how to fix it? @xavysp 

2020-06-16 16:18:50.002348: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key Xpt/output1_biases_1 not
 found in checkpoint
?[31m[16 Jun 2020 16h18m50s][ERROR] Error setting up DexiNed traied model, Restoring from checkpoint failed. This is most likely due to a Variable name or other grap
h key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Xpt/output1_biases_1 not found in checkpoint
         [[node save/RestoreV2 (defined at D:\PycharmProjects2\edge-detection-DexiNed\test.py:37) ]]

Original stack trace for 'save/RestoreV2':
  File "run_model.py", line 131, in <module>
    main(args=args)
  File "run_model.py", line 120, in main
    tester.setup(sess)
  File "D:\PycharmProjects2\edge-detection-DexiNed\test.py", line 37, in setup
    saver = tf.train.Saver()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 825, in __init__
    self.build()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 875, in _build
    build_restore=build_restore)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
?[0m
?[32m[16 Jun 2020 16h18m50s][INFO]Writing PNGs at None?[0m
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value Xpt/output6_biases_4
         [[{{node Xpt/output6_biases_4/read}}]]
         [[output_4/_523]]
  (1) Failed precondition: Attempting to use uninitialized value Xpt/output6_biases_4
         [[{{node Xpt/output6_biases_4/read}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_model.py", line 131, in <module>
    main(args=args)
  File "run_model.py", line 121, in main
    tester.run(sess)
  File "D:\PycharmProjects2\edge-detection-DexiNed\test.py", line 71, in run
    edgemap = session.run(self.model.predictions, feed_dict={self.model.images: [im]})
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value Xpt/output6_biases_4
         [[node Xpt/output6_biases_4/read (defined at D:\PycharmProjects2\edge-detection-DexiNed\models\dexined.py:290) ]]
         [[output_4/_523]]
  (1) Failed precondition: Attempting to use uninitialized value Xpt/output6_biases_4
         [[node Xpt/output6_biases_4/read (defined at D:\PycharmProjects2\edge-detection-DexiNed\models\dexined.py:290) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'Xpt/output6_biases_4/read':
  File "run_model.py", line 131, in <module>
    main(args=args)
  File "run_model.py", line 120, in main
    tester.setup(sess)
  File "D:\PycharmProjects2\edge-detection-DexiNed\test.py", line 20, in setup
    self.model = dexined(self.args)
  File "D:\PycharmProjects2\edge-detection-DexiNed\models\dexined.py", line 37, in __init__
    self.define_model()
  File "D:\PycharmProjects2\edge-detection-DexiNed\models\dexined.py", line 240, in define_model
    kernel_init=weight_init)
  File "D:\PycharmProjects2\edge-detection-DexiNed\models\dexined.py", line 397, in side_layer
    name=name, upscale=upscale, sub_pixel=sub_pixel)
  File "D:\PycharmProjects2\edge-detection-DexiNed\models\dexined.py", line 290, in upsample_block
    name=name + '_biases_{}'.format(i))
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 220, in _variable_v1_call
    shape=shape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 198, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2511, in default_variable_creator
    shape=shape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 1568, in __init__
    shape=shape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 1755, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 86, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4253, in identity
    "Identity", input=input, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by nywang2019** [comment]
by the way, i used the augmented bsds dataset provided by hed.  i justed changed a few necessary options for training and kept the remaining options the same as the original ones.

**Comment by nywang2019** [comment]
i have figured out it, thanks.

**Comment by anandhu1436** [comment]
> i have figured out it, thanks.

can you send the link of pre trained model for bsds500,
