### ISSUE TITLE
Training with run_model.py: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by za13** [xavysp/DexiNed#44]
I downloaded the checkpoint files from the google drive link and placed them in ./DexiNed-master/DexiNed-TF2/DXN_BIPED and then ran

    python run_model.py --image_width=512 --image_height=512

and got the error below

	Traceback (most recent call last):
	  File "run_model.py", line 131, in <module>
	    main(args=args)
	  File "run_model.py", line 108, in main
	    trainer.run(sess)
	  File "/home/me/Desktop/DexiNed-master/train.py", line 32, in run
	    train_data = data_parser(self.args)
	  File "/home/me/Desktop/DexiNed-master/utls/dataset_manager.py", line 1018, in data_parser
	    if args.train_dataset.lower() == 'biped' else os.path.join(args.dataset_dir, args.train_dataset)
	  File "/home/me/anaconda3/lib/python3.6/posixpath.py", line 80, in join
	    a = os.fspath(a)
	TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by xavysp** [comment]
> I downloaded the checkpoint files from the google drive link and placed them in ./DexiNed-master/DexiNed-TF2/DXN_BIPED and then ran
> 
> ```
> python run_model.py --image_width=512 --image_height=512
> ```
> 
> and got the error below
> 
> ```
> Traceback (most recent call last):
>   File "run_model.py", line 131, in <module>
>     main(args=args)
>   File "run_model.py", line 108, in main
>     trainer.run(sess)
>   File "/home/me/Desktop/DexiNed-master/train.py", line 32, in run
>     train_data = data_parser(self.args)
>   File "/home/me/Desktop/DexiNed-master/utls/dataset_manager.py", line 1018, in data_parser
>     if args.train_dataset.lower() == 'biped' else os.path.join(args.dataset_dir, args.train_dataset)
>   File "/home/me/anaconda3/lib/python3.6/posixpath.py", line 80, in join
>     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```

Hi sorry I cannot reproduce the error, it works perfectly.

**Comment by claudia-new** [comment]
Hey, I encounter the same problem, have you solved it?

**Comment by claudia-new** [comment]
> I downloaded the checkpoint files from the google drive link and placed them in ./DexiNed-master/DexiNed-TF2/DXN_BIPED and then ran
> 
> ```
> python run_model.py --image_width=512 --image_height=512
> ```
> 
> and got the error below
> 
> ```
> Traceback (most recent call last):
>   File "run_model.py", line 131, in <module>
>     main(args=args)
>   File "run_model.py", line 108, in main
>     trainer.run(sess)
>   File "/home/me/Desktop/DexiNed-master/train.py", line 32, in run
>     train_data = data_parser(self.args)
>   File "/home/me/Desktop/DexiNed-master/utls/dataset_manager.py", line 1018, in data_parser
>     if args.train_dataset.lower() == 'biped' else os.path.join(args.dataset_dir, args.train_dataset)
>   File "/home/me/anaconda3/lib/python3.6/posixpath.py", line 80, in join
>     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```

Hi, I have the same problem, Could you share how did you fix that?
